version: 2

jobs:
  build:
    docker:
      - image: secoresearch/apache-varnish:latest
    steps:
    - checkout
    - setup_remote_docker
    - run: docker login -u sri6379 -p Rgs454***
            

workflows:
  version: 2
  build-project:
    jobs:
      - build

       