version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
        auth:
          username: sri6379
          password: Rgs454***
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        apt-get update
        apt install python3 -y
        
workflows:
  version: 2
  build-project:
    jobs:
      - build

       