version: 2

jobs:
  build:
    docker:
      - image: ubuntu:latest
        auth:
          username: sri6379
          password: Rgs454***
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        apt-get install docker-engine -y
        service docker start
        docker run hello-world
workflows:
  version: 2
  build-project:
    jobs:
      - build

       