version: 2

jobs:
  build:
    docker:
      - image: secoresearch/apache-varnish:latest
        auth:
          username: sri6379
          password: Rgs454***
    steps:
    - checkout
    - setup_remote_docker
    - run: docker build sri6379/demoimage:v1 .
workflows:
  version: 2
  build-project:
    jobs:
      - build

       