version: 2

jobs:
  build:
    docker:
      - image: secoresearch/apache-varnish:latest
    steps:
    - checkout
    - setup_remote_docker
    - run: echo "build success"

workflows:
  version: 2
  build-project:
    jobs:
      - build

       